/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-dim": "#d9dadc",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f1f3",
        "on-primary-fixed-variant": "#173bab",
        "secondary": "#525c87",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8ea",
        "tertiary": "#003d27",
        "outline": "#757684",
        "primary": "#00288e",
        "secondary-fixed-dim": "#bbc4f6",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#3b446e",
        "background": "#f8f9fb",
        "secondary-container": "#c3ccfe",
        "on-secondary-fixed": "#0e1840",
        "surface-bright": "#f8f9fb",
        "primary-container": "#1e40af",
        "on-surface-variant": "#444653",
        "outline-variant": "#c4c5d5",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#3fd298",
        "on-primary-container": "#a8b8ff",
        "on-primary": "#ffffff",
        "primary-fixed": "#dde1ff",
        "inverse-primary": "#b8c4ff",
        "surface": "#f8f9fb",
        "surface-tint": "#3755c3",
        "surface-variant": "#e1e2e4",
        "on-secondary-container": "#4c5680",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "tertiary-container": "#00563a",
        "secondary-fixed": "#dde1ff",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed": "#001453",
        "surface-container": "#edeef0",
        "surface-container-low": "#f3f4f6",
        "on-tertiary-fixed": "#002113",
        "on-background": "#191c1e",
        "surface-container-highest": "#e1e2e4"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "inter": ["Inter"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
